lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
mixlib-shellout-windows.gemspec

windows-pr includes everything under the sun.
This is means it does not work no nanoserver
cc @adamedx @chefsalim @ksubrama @mcquin

Remove dependency on windows-pr

---

CHANGELOG.md
lib/mixlib/shellout/version.rb

Thoughts on release this gem?
cc @lamont-granquist @thommay @danielsdeleo

Bump version to 2.2.0

---

mixlib-shellout.gemspec

Add gemspec files to allow bundler to run from the gem

---

CHANGELOG.md
lib/mixlib/shellout/version.rb
lib/mixlib/shellout/windows.rb
mixlib-shellout-windows.gemspec
mixlib-shellout.gemspec
spec/mixlib/shellout_spec.rb

~~This is currently intended to be a private copy to give to a customer. If it fixes them we will add a option to turn it on and do so only in the windows service watch dog.~~
Now ready for review.

Kill windows child proicesses when comand times out

---

.travis.yml
README.md
lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
mixlib-shellout.gemspec

Improve the formatting of the readme and better document more advanced shellout
Update travis config to a more modern config
Add badges to the readme
Opscode -> Chef
Copyright updates

Improve documentation + misc fixes

---

lib/mixlib/shellout/exceptions.rb

Modified all exceptions to have a common parent

---

.rubocop.yml
.travis.yml
Gemfile
README.md
Rakefile
appveyor.yml
lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
mixlib-shellout-windows.gemspec
mixlib-shellout.gemspec
spec/mixlib/shellout/windows_spec.rb
spec/mixlib/shellout_spec.rb
spec/spec_helper.rb

Require Ruby 2.2
Add chefstyle to the gemspec/rakefile and resovle warnings
Have Travis use Rake so it lints
Add contributing doc link

Require Ruby 2.2 and use chefstyle

---

.travis.yml

Test on Ruby 2.4.0 in Travis

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/exceptions.rb
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb

trying to move towards reducing code duplication with chef/chef

mostly cleanup which helper

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

fix chefstyle offenses

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
spec/mixlib/shellout_spec.rb

Addressing feedback on https://github.com/chef/mixlib-shellout/pull/148 to expedite.

Added `elevated` option to launch process with elevated privileges

---

README.md

Relevant PR: https://github.com/chef/mixlib-shellout/pull/148

[README] Added example for elevated privileges

---

.rubocop.yml
lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout_spec.rb

Support added as a part of PR chef/chef#7353
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>

[MSYS-830] Added sensitive feature

---

.rubocop.yml
Gemfile
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout_spec.rb
spec/spec_helper.rb

Signed-off-by: Lamont Granquist <lamont@scriptkiddie.org>

remove hashrocket syntax

---

.travis.yml
Rakefile
appveyor.yml
mixlib-shellout.gemspec

Also skip the tests when expeditor commits.

Test on ruby-head and Ruby 2.6 in Travis

---

Gemfile
mixlib-shellout.gemspec

These are all in the gemfile now

Remove dev deps from the gemspec

---

mixlib-shellout.gemspec

Don't ship the readme in the gem artifact

---

README.md

Super quick fix for something that bit me from the README and later clarified in the docs of the method in the code. This should hopefully help a newcomer wanting to use this.
None

Misnamed parameter in README

---

.expeditor/config.yml
.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/PULL_REQUEST_TEMPLATE.md
.github/lock.yml
.travis.yml
CONTRIBUTING.md

This syncs our config here with our other repos

Add new github templates and codeowners file

---

.expeditor/config.yml

Add BuildKite pipeline

---

.expeditor/verify.pipeline.yml
.rubocop.yml
Gemfile
appveyor.yml

Don't install the world and skip chefstyle from git which is rather slow.

Speedup CI tests

---

.expeditor/verify.pipeline.yml
appveyor.yml

Switch to official ruby containers in buildkite
Cache bundler and use a newer box in appveyor

More CI Speedups

---

.expeditor/verify.pipeline.yml
Gemfile

Test what we support
Signed-off-by: Tim Smith <tsmith@chef.io

Add Ruby 2.2 and 2.3 testing

---

Rakefile
lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
spec/mixlib/shellout_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb

Signed-off-by: Ryan Davis <zenspider@chef.io>

Blinding applying chefstyle -a.

---

README.md
lib/mixlib/shellout.rb

Fix some small problems I found in the docs.

Minor doc fixes

---

README.md

Forgot to do this in the last PR.

Bumping minor version

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
.rspec
.rubocop.yml
Gemfile
spec/mixlib/shellout_spec.rb

Modernize this CI setup to match our other stuff.

Test on Ruby 2.7 final, update chefstyle, and other CI fixes

---

README.md

Bump minor for release

---

README.md

Bumping minor for release again, again.

---

README.md

Bump minor

---

README.md

need a new build for expeditor

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/helper.rb
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb
spec/mixlib/shellout_spec.rb

Fix a few typos

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
Gemfile

Add Ruby 3 testing + cleanup deps

---

.expeditor/config.yml
.expeditor/run_windows_tests.ps1
.expeditor/verify.pipeline.yml
.github/CODEOWNERS
CHANGELOG.md
Gemfile
mixlib-shellout-universal-mingw-ucrt.gemspec
mixlib-shellout.gemspec
spec/mixlib/shellout_spec.rb

Signed-off-by: John McCrae <jmccrae@chf.io>

Hard Coding the gems in the gemfile to overcome a Ruby 3.1 bug

---

.expeditor/verify.pipeline.yml

Signed-off-by: poornima <poorndm@progress.com>

Add ruby 3.0 test on windows

---

lib/mixlib/shellout/helper.rb

This makes minor adjustments to the Target Mode specific functionality.

Adjustments for Chef Target Mode

---

.rubocop.yml
Gemfile
Rakefile
spec/mixlib/shellout_spec.rb

Migrate from Chefstyle to Cookstyle

---

lib/mixlib/shellout/unix.rb

Set timeout to zero for last select (#245)

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
.rubocop.yml
Rakefile
mixlib-shellout-universal-mingw32.gemspec
mixlib-shellout.gemspec

We are formally moving away from chefstyle to cookstyle.

migrating to cookstyle from chefstyle

---

.expeditor/run_windows_tests.ps1

Adding cookstyle tests to the windows testers to ensure full coverage

Adding cookstyle to the windows tester

---

.expeditor/verify.pipeline.yml
.gitignore
.rubocop.yml
lib/mixlib/shellout/windows.rb
mixlib-shellout.gemspec
spec/mixlib/shellout_spec.rb

This PR updates the ruby version to >= 3.1
JIRA: https://progresssoftware.atlassian.net/browse/CHEF-20551

ruby 3.4 upgrade
