chef/mixlib-shellout

README.md

Fixed a simple transposition of characters.

README: typo in example

---

spec/mixlib/shellout_spec.rb

This test was not passing on my local box without explicitly calling powershell -c.

Change mixlib spec test to pass on windows by invoking powershell explicitly.

---

Gemfile
Rakefile
mixlib-shellout-windows.gemspec
mixlib-shellout-x86-mingw32.gemspec

Since we don't actually have platform specific code, only dependencies, we can use this structure to generate gems based on just the ABI needed.  Hence we have a mingw32 package (supports both 32 and 64-bit outputs) and an mswin32 package (good luck fellas..).  We also have a pure ruby output for test purposes.

Refactor platform dependent gem creation.

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
spec/mixlib/shellout_spec.rb

Added:
* Secondary groups from etc files
* Set environment variables like `su` would
* Set primary group to user's primary group if no other group specified
All only if `with_logon` is set
Fixes #77

with_logon now simulates login in unix

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
spec/spec_helper.rb

I enabled ruby warnings on the chef-config subproject, and got a ton of warning spam from shellout. Adding warnings to the tests here revealed these two issues.
@chef/client-core

Fix 2 ruby warnings for uninitialized variables

---

lib/mixlib/shellout/unix.rb
spec/mixlib/shellout_spec.rb

POSIX standard defines setsid() to set the pgid to the pid of the calling process.  Use that to fix our race conditions and funkiness around setpgrp()/getpgrp().  Use setsid() again to remove the controlling tty.
fixes #93

remove getpgrp back to setsid

---

spec/mixlib/shellout_spec.rb

This is breaking on windows with ruby 2.0.0p645. The issue
seems to be that there is something at the fd, but it's not
the file descriptor from the parent.
Instead, we're now testing that both the fd exists and
the file contains the contents that were written

Don't use presence of fd to check if fd's were inherited 

---

lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb

ruby considers directories to be executable. This seems to be true for both linux and windows, however the shellout logic on windows uses `executable?` to determine if a path is executable. When trying to find the correct path to run, shellout starts with just the command given (ie `knife`) to see if there is an executable by the same name in the current directory. So if the user so happens to have a directory with that same name, an exception is raised:
```
Input/output error - CreateProcessW (Errno::EIO)
```
Because we are attempting to create a process with the directory.
This fixes https://github.com/chef/chef-dk/issues/482

prevent shellout from attempting to execute a directory on windows

---

lib/mixlib/shellout.rb
spec/mixlib/shellout_spec.rb

By converting the hash keys to strings, we can use symbols in our environment blocks with the pretty, new Ruby 1.9 hash style:
```
environment {FOO: 'bar', SHELL: 'zsh'}
```
I was initially going to place this at https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout/unix.rb#L174 but it looks like there's no way to write tests for that, and would require repeating it for Windows too.
@jordane

convert environment hash keys to strings

---

.travis.yml
appveyor.yml
lib/mixlib/shellout/windows/core_ext.rb

this fixes https://github.com/chef/chef/issues/4464 introduced with https://github.com/chef/mixlib-shellout/commit/c302f8c61d8d50da4d4797d583fecc18a0a8bd1c 
That changed several bool parameters to int and accommodated a downstream change to `CreateProcessW` which changed the `inherits` arg from `:bool` to `int` (see https://github.com/djberg96/win32-process/pull/20). However the `CreateProcessAsUserW` function defined here is a `:bool` and breaks when passed an int.
I think ultimately it would be better for the downstream `CreateProcessW` to revert to a `bool` and keep these two consistent.
Both functions `inherit` args are documented as `:bool` in the following links:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682429(v=vs.85).aspx …

fixes regression where CreateProcessWithLogonW wants a boolean

---

Gemfile
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb

After making more aggressive use of timeouts in Ohai, there was a report of BSOD's on Windows servers before Chef Client could run.  The error logs indicated that ruby was killing csrss.exe.
While I haven't been able to repro the error, there are several processes that, if killed, can destabilize and likely bug-check (blue screen) Windows - so I added a check in `Mixlib::ShellOut::Windows::Utils#kill_process_tree` to skip those potentially destabilizing processes when we recursively kill child processes.
Troubleshooting by the reporting party of https://github.com/chef/chef/issues/4920 noted that there may be an instance where some core processes are returned when an improper process ID is passed along.  
The only other scenario I can think of (but haven't been able to replicate yet) is …

Keep Mixlib-ShellOut from killing required Windows processes

---

.travis.yml
mixlib-shellout.gemspec
spec/mixlib/shellout_spec.rb
spec/support/platform_helpers.rb

Just removes some 1.9 logic from testing.

Require Ruby 2.1+

---

Rakefile

current `:ship` task does not work and this is way simpler

use gem helper tasks to get rake release

---

.travis.yml
Rakefile
appveyor.yml
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb
spec/mixlib/shellout_spec.rb

its just a collection of private methods, they should be private methods

remove largely useless Utils class

---

lib/mixlib/shellout/exceptions.rb

Chef rescues Mixlib::ShellOut::ShellCommandFailed, SystemCallError in a few places.
Recent refactors caused EmptyWindowsCommand to be correctly raised where we still
unintentionally raised SystemCallError due to a bad FFI call. This gets us closer
to not needing to cover these edge cases in rescue clauses everywhere.
Signed-off-by: Bryan McLellan <btm@chef.io>

Make Mixlib::ShellOut::EmptyWindowsCommand inherit from ShellCommandFailed

---

.rubocop.yml
lib/mixlib/shellout/windows.rb
mixlib-shellout-windows.gemspec

To fix rubocop errors we removed the rescues in earlier PR https://github.com/chef/mixlib-shellout/pull/157/files#diff-a49639dc02ce0578d8000ee0aecf5210.
So we have added them back here again to make those as specific as possible.
Added `SystemCallError` to make the rescues as specific as possible because it is parent of `Errno::EIO` and will cover all required error now.

Fix a bare rescue on Windows

---

lib/mixlib/shellout/windows.rb

On Windows if the command is not quoted but has spaces in leading, the function `candidate_executable_for_command` returns nothing, by example:
```
java_oracle_install[jre] had an error: Mixlib::ShellOut::EmptyWindowsCommand: could not parse script/executable out of command: ` tar xvzf "c:/chef/cache/jre-8u131-windows-x64.tar.gz" -C "c:/chef/cache" --no-same-owner`
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.3.2-universal-mingw32/lib/mixlib/shellout/windows.rb:197:in `command_to_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.3.2-universal-mingw32/lib/mixlib/shellout/windows.rb:61:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.3.2-universal-mingw32/lib/mixlib/shellout.rb:263:in `run_command' …
```

Avoid EmptyWindowsCommand error on Windows when the command starts with spaces

---

Rakefile
lib/mixlib/shellout/windows.rb
spec/mixlib/shellout/windows_spec.rb

Implements correct quoting and escaping of arguments on windows.
That means that this works right now:
```ruby
filename = 'c:\program files'
shell_out('dir', filename);
```
So all the defensive coding around quotes-around-filepaths -- which were
all actually buggy even when they worked (trailing backslashes would
fail) -- are unnecessary and arguments can just be passed in as an array
and this code will sort it out.
We rely on the existing determination of if metacharacters mean it needs
to run under cmd and if it needs the ^ quoting which seems to be well
tested, and which all runs after this does.

Support array args on windows WIP

---

lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb

- bind related C++ funcs, add types and constants
- refactor similar func calls into component methods
- make Process#create return trio of process-related objects
- ensure delayed profile unload and token destruction
Signed-off-by: Brian Warsing <brian.warsing@visioncritical.com>
When `elevated: true` or running in a "service window station", loads and unloads the given `logon` user's profile, as required.
Related Issue: #168
Notes:
Due to the complexities involved, I have elected not to include support for
roaming profiles. As such, if `Process#create` calls `CreateProcessAsUserW` and the `logon` has roaming profile, `Mixlib` will raise an `UnsupportedFeature`
exception. Also, I have not included a **feature toggle** for profile loading, but would be happy to do so...

Load and unload user profile as required

---

lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb

This fixes compatibility with win32-process' Process.create while
maintaining the rest of our changes.
The break came from PR #177, which is fairly extensive, so I'm only
rolling out the return type change on this method.
Signed-off-by: Ryan Davis <zenspider@chef.io>

Fix return type of Process.create to be a ProcessInfo instance again.

---

.github/lock.yml
README.md
lib/mixlib/shellout.rb
lib/mixlib/shellout/windows.rb

require_relative is significantly faster and should be used when available.

Substitute require for require_relative

---

spec/mixlib/shellout_spec.rb

There is no guarantee that ENV["USER"] is always present, and in some
environments, it's not. Get the current user from Etc.getpwuid, which
works even in the absence of any environment variables.

shellout_spec: make "current user" independent of the environment

---

.expeditor/run_linux_tests.sh
.expeditor/verify.pipeline.yml
lib/mixlib/shellout/helper.rb
mixlib-shellout.gemspec
spec/mixlib/shellout/helper_spec.rb
spec/spec_helper.rb
spec/support/dependency_helper.rb

See the spec test for a trivial example of doing the dep injection of your own logger, train connection and config hash.
Mostly this is offered just to provide code sharing between chef, ohai and other internal chef projects.  It is deliberately left undocumented and we might violate SemVer from time to time (as far as the private dependency-injection part of the API goes, we can't violate SemVer on the ultimate consumer-facing interface of the shell_out helper -- but if you use this in other software we might break you).

extracting shell_out helper to mixlib-shellout

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/helper.rb

require is quite slow in Ruby and doing requires for things you've already required is also slow. We've used this simple hack in Chef to speed up our requires. In the omnibus installs we patch how rubygems works to make this somewhat pointless, but this will help non-omnibus installs

Optimize requires for non-omnibus installs

---

lib/mixlib/shellout/helper.rb
spec/mixlib/shellout/helper_spec.rb

This has to have been an oversight when thom created the trace
level, since live stdout logging produces a lot of output.
We also need this for adding live stdout logging for ohai which
produces a lot of output, where trace is certainly more
appropriate and makes the debug level difficult to read.

Drop the shell_out logging down to trace level

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
spec/mixlib/shellout_spec.rb

Use the latest and greatest ruby-isms to cut down on some code.

Simplify things a bit with &.

---

mixlib-shellout-universal-mingw32.gemspec
spec/spec_helper.rb

This removes the use of $SAFE which is causing deprecation warnings when killing processes on Windows.

Loosen win32-process dep to resolve Ruby 3 deprecation warnings

---

lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb
mixlib-shellout-universal-mingw32.gemspec
spec/mixlib/shellout_spec.rb

Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>
- Added `CreateEnvironmentBlock` function for fetching environment variables for the specified user.
- Added `DestroyEnvironmentBlock` function for free environment variables after reading, which is created by the `CreateEnvironmentBlock` function
https://github.com/chef/chef/issues/7690

Windows: fetch env variables for specified users

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
lib/mixlib/shellout/windows.rb
lib/mixlib/shellout/windows/core_ext.rb

This is 100% just to force a new build since 3.2.0 was build off the master branch and not main, which caused some old code to ship. We need a 3.2.1

Remove copyright dates

---

Gemfile
Rakefile
spec/spec_helper.rb

These do no get used by this project.

Cleanup deps and fix the failing spec helper loading of support files

---

.expeditor/verify.pipeline.yml
spec/mixlib/shellout_spec.rb

This fixes broken windows tests by:
1. Running docker build as `NT AUTHORITY\SYSTEM` which will have sufficient privileges to impersonate users.
2. Copying `Powershell.exe` instead of `ruby.exe` to a command with a space. Some (likely most) ruby distributions like the one in the buildkite docker image will also need several DLLs copied along with the `exe` in order to work. Powershell does not have that problem.

fix broken windows tests

---

mixlib-shellout.gemspec

so the data is visible on e.g. rubygems.org and can be used by compliance tooling. 
Unchecked box do not apply IMO, as this is a non-functional change

gemspec: add license metadata

---

lib/mixlib/shellout.rb

Signed-off-by: Clinton Wolfe <clintoncwolfe@gmail.com>
Causing test failures on InSpec here (not our only problem) - https://buildkite.com/chef-oss/inspec-inspec-main-verify/builds/4314#4c315e88-e205-42dc-8536-22aae8fef418
Fixes #233

Loosen platform regex to allow 64 or 32 bit mingw

---

.expeditor/verify.pipeline.yml
Gemfile

* `ffi` `1.17` and beyond requires a newer RubyGems than is installed with the ruby versions we are using.
* Remove tests for Ruby < 2.7
* Remove Gemfile conditional for Ruby < 2.7
See also [ffi/ffi#1106](https://github.com/ffi/ffi/issues/1106)

Keep ffi version below 1.17

---

lib/mixlib/shellout/windows.rb

This is simply a rebased version of #239, as I don't want finished work to hit the floor.

[#239] Add execution time to Windows shellout object

---

spec/mixlib/shellout_spec.rb

On systems with larger page sizes, more bytes are required in order to trigger an EPIPE.  Tested on 8k and 64k systems.
https://github.com/chef/mixlib-shellout/issues/204

Increase EPIPE test input size based on platform page size

---

lib/mixlib/shellout/helper.rb

This solves a bug when executing commands in Chef Infra Target Mode, when a new working directory is passed with the `cwd` option. Mostly related to the `git`, `freebsd_package`, and `subversion` resources.

Fix execution in target mode with cwd parameter given

---

lib/mixlib/shellout/helper.rb

Multiline inputs to Target Mode commands were ignored due to an implementation bug. This is fixed and also, errors will result in the output of `stderr` for debugging purposes.

Fix execution of multiline inputs to target mode; Improve error output

---

lib/mixlib/shellout/helper.rb

This fixes the convoluted code to join arguments of a command in Target Mode. This now automatically quotes arguments which contain spaces. Fixes Chef Intra 19.0-rc1 errors on `user` with multi word comments.

Fix quoting of command arguments in Target Mode

---

lib/mixlib/shellout/helper.rb

This fixes the quoting regression introduced with my code changes in 3.3.4
Failure of most resources in Chef 19 Target Mode with "Exit code 127"

Fix quoting regression

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/unix.rb
spec/mixlib/shellout_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb

This PR aims to implement cgroupv2 support for shellouts, allowing the user to specify under which cgroup should the command be executed.

Add cgroupv2 support for linux shellouts

---

Gemfile
mixlib-shellout.gemspec

* Kept ffi pin for older ruby's since that's required.
* Did not use `install_if`, as it seems quite buggy still
* Bumped the min ruby as it was ancient.
Signed-off-by: Phil Dibowitz <phil@ipom.com>

Drop the FFI pin

---

mixlib-shellout-universal-mingw-ucrt.gemspec

This PR tries to fix the issue with `bundle install` on linux that was popping up on `main` after https://github.com/chef/mixlib-shellout/pull/261 was merged while there was no error in CI before merging. However this change has been tested on a docker container with the same image used in pipeline and seems to be working now.

attempting to fix the bundler error

---

Gemfile

handling the warnings for ruby 3.5 that were added in 3.4
```
warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
```
JIRA: https://progresssoftware.atlassian.net/browse/CHEF-20948

add logger as an explicit dependency

---

lib/mixlib/shellout.rb
lib/mixlib/shellout/windows/core_ext.rb
spec/mixlib/shellout_spec.rb

updating the initalisation because of ruby 3.4 warnings since ruby 4.0 is going to freeze strings by default. 
related issue: #257 
JIRA: https://progresssoftware.atlassian.net/browse/CHEF-20948

assign @stdout, @stderr and @process_status to mutable strings in preparation for ruby 4.0

---

README.md

This pull request removes the oft-misleading Chef SLA text from the README.md file.
This action is being taken as part of the [2025 Repo Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025). 
As Progress Chef makes a best effort to respond to issues and pull requests in a timely manner, and prioritizes bugfixes and security updates on a customer-driven basis (which may span repos, or have no repo footprint at all), we no longer support the concept of a Service Level Agreement (SLA) on a repository-centric basis. For further details, see [Repo SLA Removal FAQ](https://github.com/chef-boneyard/oss-repo-standardization-2025/blob/main/messaging/sla-removal.md).

CHEF-25794 - standardize - remove_sla_from_readme
